ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avgVocabulary" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avgComplexity" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avgFluency" INTEGER NOT NULL DEFAULT 50;
