'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Share2, Download, X, Twitter, MessageCircle, Send, Camera, Grid3X3 } from 'lucide-react';
import { toast } from 'sonner';

interface ShareActionProps {
  text: string;
  persona: string;
  weakness?: string | null;
  className?: string;
  messages?: Array<{ text: string; sender: 'user' | 'ai' }>;
  referralCode?: string | null;
  forceOpen?: boolean;
  onForceClose?: () => void;
}

export function ShareAction({ text, persona, weakness, className, messages = [], referralCode, forceOpen, onForceClose }: ShareActionProps) {
  const [isSharing, setIsSharing] = useState(false);
  const [showModal, setShowModal] = useState(forceOpen ?? false);
  const [shareMode, setShareMode] = useState<'single' | 'conversation'>('single');

  // Sync showModal with forceOpen prop so parent can toggle it dynamically
  useEffect(() => {
    if (forceOpen !== undefined) setShowModal(forceOpen);
  }, [forceOpen]);

  const generateShareContent = () => {
    if (shareMode === 'conversation' && messages.length > 0) {
      const conversationText = messages
        .slice(-3) // Take last 3 messages for snippet
        .map(msg => `${msg.sender === 'user' ? 'You' : persona}: "${msg.text}"`)
        .join('\n');
      return `${conversationText}\n\n— Generated by Aura OS`;
    }
    return `${persona}: "${text}" - Generated by Aura OS`;
  };

  const generateViralImage = async () => {
    // Fetch the premium server-rendered OG image from /api/share
    // instead of the crude client-side canvas approach.
    const params = new URLSearchParams({
      text: text.slice(0, 280),
      persona,
      ...(weakness ? { weakness } : {}),
      ...(shareMode === 'conversation' && messages.length > 0
        ? { messages: JSON.stringify(messages.slice(-4).map(m => ({ text: m.text.slice(0, 120), sender: m.sender }))) }
        : {}),
    });

    const res = await fetch(`/api/share?${params.toString()}`);
    if (!res.ok) throw new Error('Image generation failed');
    const blob = await res.blob();
    return URL.createObjectURL(blob);
  };

  const handleDownloadOGImage = async (platform: 'instagram' | 'tiktok') => {
    const objectUrl = await generateViralImage();
    const link = document.createElement('a');
    link.download = `aura-${platform}-${Date.now()}.png`;
    link.href = objectUrl;
    link.click();
    // Revoke object URL after a short delay to free memory
    setTimeout(() => URL.revokeObjectURL(objectUrl), 5000);
    toast.success(`Premium card downloaded! Upload to ${platform === 'instagram' ? 'Instagram Stories' : 'TikTok'}`, {
      description: 'Your Aura card is ready to share.',
      duration: 5000,
    });
  };


  const handleShare = async (method?: 'twitter' | 'telegram' | 'clipboard' | 'instagram' | 'tiktok') => {
    setIsSharing(true);
    
    try {
      const shareText = generateShareContent();
      const baseUrl = typeof window !== 'undefined' ? window.location.href.split('?')[0] : '';
      const shareUrl = referralCode ? `${baseUrl}?ref=${referralCode}` : baseUrl;
      
      if (method === 'instagram' || method === 'tiktok') {
        await handleDownloadOGImage(method);
      } else if (method === 'twitter') {
        const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`;
        window.open(twitterUrl, '_blank', 'width=550,height=420');
        toast.success('Opened Twitter share');
      } else if (method === 'telegram') {
        const telegramUrl = `https://t.me/share/url?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(shareText)}`;
        window.open(telegramUrl, '_blank', 'width=550,height=420');
        toast.success('Opened Telegram share');
      } else {
        // Clipboard fallback
        if (navigator.clipboard && navigator.clipboard.writeText) {
          await navigator.clipboard.writeText(shareText);
          toast.success('Text copied to clipboard');
        } else {
          // Ultimate fallback: use document.execCommand for older browsers
          const textArea = document.createElement('textarea');
          textArea.value = shareText;
          textArea.style.position = 'fixed';
          textArea.style.left = '-999999px';
          textArea.style.top = '-999999px';
          document.body.appendChild(textArea);
          textArea.focus();
          textArea.select();
          
          try {
            const successful = document.execCommand('copy');
            document.body.removeChild(textArea);
            
            if (successful) {
              toast.success('Text copied to clipboard');
            } else {
              throw new Error('Copy command failed');
            }
          } catch (fallbackError) {
            document.body.removeChild(textArea);
            throw fallbackError;
          }
        }
      }
      
      if (onForceClose) onForceClose();
      else setShowModal(false);
    } catch (error) {
      console.error('Share error:', error);
      toast.error('Share failed - please try again');
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <>
      {!forceOpen && (
        <motion.button
          whileTap={{ scale: 0.9 }}
          whileHover={{ scale: 1.05 }}
          onClick={() => setShowModal(true)}
          disabled={isSharing}
        className={`
          p-2 rounded-lg transition-all duration-200
          ${isSharing 
            ? 'bg-white/10 cursor-not-allowed' 
            : 'bg-white/5 hover:bg-white/10 border border-white/10 hover:border-white/20 light:bg-black/5 light:hover:bg-black/10 light:border-black/10 light:hover:border-black/20'
          }
          ${className}
        `}
        title="Share this conversation"
      >
        {isSharing ? (
          <motion.div
            animate={{ rotate: 360 }}
            transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
          >
            <Download className="w-4 h-4 text-white/60 light:text-black/60" />
          </motion.div>
        ) : (
          <Share2 className="w-4 h-4 text-white/60 light:text-black/60" />
          )}
        </motion.button>
      )}

      <AnimatePresence>
        {(showModal || forceOpen) && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm z-[9999] flex items-center justify-center p-4"
            onClick={() => { if (onForceClose) onForceClose(); else setShowModal(false); }}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              transition={{ type: 'spring', stiffness: 350, damping: 25 }}
              className="relative flex flex-col items-center gap-6 px-10 py-12 rounded-[40px] max-w-md w-full mx-4 overflow-hidden"
              style={{
                background: 'linear-gradient(135deg, rgba(15,15,20,0.95) 0%, rgba(5,5,10,0.98) 100%)',
                border: '1px solid rgba(255,255,255,0.05)',
                boxShadow: '0 40px 100px -10px rgba(0,0,0,0.8), inset 0 1px 0 rgba(255,255,255,0.05)',
              }}
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between w-full mb-4">
                <h3 className="text-lg font-semibold text-white light:text-black">Share Conversation</h3>
                <button
                  onClick={() => {
                    if (onForceClose) onForceClose();
                    else setShowModal(false);
                  }}
                  className="p-1 rounded-lg hover:bg-white/10 light:hover:bg-black/10 transition-colors"
                >
                  <X className="w-5 h-5 text-white/60 light:text-black/60" />
                </button>
              </div>

              <div className="mb-4">
                <div className="flex items-center justify-between mb-3">
                  <p className="text-sm text-white/80 light:text-black/80">
                    Share content:
                  </p>
                  <div className="flex gap-2">
                    <button
                      onClick={() => setShareMode('single')}
                      className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors ${
                        shareMode === 'single'
                          ? 'bg-[var(--accent-cyan)] text-white'
                          : 'bg-white/10 light:bg-black/10 text-white/70 light:text-black/70'
                      }`}
                    >
                      Single Message
                    </button>
                    {messages.length > 0 && (
                      <button
                        onClick={() => setShareMode('conversation')}
                        className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors flex items-center gap-1 ${
                          shareMode === 'conversation'
                            ? 'bg-[var(--accent-cyan)] text-white'
                            : 'bg-white/10 light:bg-black/10 text-white/70 light:text-black/70'
                        }`}
                      >
                        <Grid3X3 className="w-3 h-3" />
                        Conversation
                      </button>
                    )}
                  </div>
                </div>
                <div className="p-3 bg-white/5 light:bg-black/5 rounded-lg border border-white/10 light:border-black/10">
                  <p className="text-sm text-white light:text-black italic">
                    {shareMode === 'conversation' && messages.length > 0
                      ? messages.slice(-3).map((msg, idx) => (
                          <span key={idx}>
                            {msg.sender === 'user' ? 'You' : persona}: "{msg.text}"
                            {idx < Math.min(2, messages.length - 1) && '\n'}
                          </span>
                        ))
                      : `"${text}"`
                    }
                  </p>
                  <p className="text-xs text-white/60 light:text-black/60 mt-2">
                    — {persona} • Aura OS
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3 mb-3">
                <motion.button
                  whileTap={{ scale: 0.95 }}
                  whileHover={{ scale: 1.02 }}
                  onClick={() => handleShare('twitter')}
                  className="flex items-center justify-center gap-2 p-3 bg-[#1DA1F2] light:bg-[#1DA1F2] text-white rounded-xl transition-colors hover:bg-[#1a91da]"
                >
                  <Twitter className="w-4 h-4" />
                  <span className="text-sm font-medium">Twitter</span>
                </motion.button>

                <motion.button
                  whileTap={{ scale: 0.95 }}
                  whileHover={{ scale: 1.02 }}
                  onClick={() => handleShare('telegram')}
                  className="flex items-center justify-center gap-2 p-3 bg-[#0088cc] light:bg-[#0088cc] text-white rounded-xl transition-colors hover:bg-[#0077b5]"
                >
                  <Send className="w-4 h-4" />
                  <span className="text-sm font-medium">Telegram</span>
                </motion.button>

                <motion.button
                  whileTap={{ scale: 0.95 }}
                  whileHover={{ scale: 1.02 }}
                  onClick={() => handleShare('instagram')}
                  className="flex items-center justify-center gap-2 p-3 bg-gradient-to-r from-[#F58529] via-[#DD2A7B] to-[#8134AF] light:from-[#F58529] light:via-[#DD2A7B] light:to-[#8134AF] text-white rounded-xl transition-all hover:shadow-lg"
                >
                  <Camera className="w-4 h-4" />
                  <span className="text-sm font-medium">Instagram</span>
                </motion.button>

                <motion.button
                  whileTap={{ scale: 0.95 }}
                  whileHover={{ scale: 1.02 }}
                  onClick={() => handleShare('tiktok')}
                  className="flex items-center justify-center gap-2 p-3 bg-black light:bg-black text-white rounded-xl transition-colors hover:bg-gray-800"
                >
                  <Camera className="w-4 h-4" />
                  <span className="text-sm font-medium">TikTok</span>
                </motion.button>
              </div>

              <motion.button
                whileTap={{ scale: 0.95 }}
                whileHover={{ scale: 1.02 }}
                onClick={() => handleShare('clipboard')}
                className="flex items-center justify-center gap-2 p-3 bg-white/10 light:bg-black/10 text-white light:text-black border border-white/20 light:border-black/20 rounded-xl transition-colors hover:bg-white/20 light:hover:bg-black/20 w-full"
              >
                <Download className="w-4 h-4" />
                <span className="text-sm font-medium">Copy to Clipboard</span>
              </motion.button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
